### ISSUE TITLE
files should be kept in which directory

### ISSUE THREAD

**Issue by cksachdev** [s3thi/webstorm-settings#1]
I have downloaded the master and kept the files in /Users/Sachdev/Library/Preferences/WebStorm2016.2/options directory.
But none of the settings are getting applied in Webstorm. Please mention in which directory, these files should be kept.

**Comment by s3thi** [comment]
This is just a backup of my settings (you can set yours up by going to `Settings -> Settings Repository...`). You shouldn't be using this.

**Comment by cksachdev** [comment]
OK. is there a way that I can import these settings. e.g. sharing the webstorm settings with the development team?

**Comment by s3thi** [comment]
WebStorm's backup system wasn't built for teams. Use http://editorconfig.org/ for that.
